# Generated by Django 4.2 on 2024-04-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_user',
            new_name='event_user_id',
        ),
    ]
