# Generated by Django 4.2 on 2024-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_user_id',
            new_name='event_user',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=30),
        ),
    ]
