# Generated by Django 4.2 on 2024-03-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_customuser_email_id_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
